metric: COCO
num_classes: 3

TrainDataset:
  name: COCODataSet
  image_dir: images_train_wt
  anno_path: annotations/instance_train_wt.json
  dataset_dir: E:\data\0111_testdata\data_labeled4254\coco5_wt
  data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']
  allow_empty: true

EvalDataset:
  name: COCODataSet
  image_dir: images_val_wt
  anno_path: annotations/instance_val_wt.json
  dataset_dir: E:\data\0111_testdata\data_labeled4254\coco5_wt
  allow_empty: true

TestDataset:
  name: ImageFolder
  anno_path: annotations/instance_train.json # also support txt (like VOC's label_list.txt)
  dataset_dir: E:\data\0111_testdata\data_labeled\slice_coco2560
