dataset_path: &dataset_path /mnt/e/data/DefectDet/

metric: COCO
num_classes: 7

TrainDataset:
  name: COCODataSet
  image_dir: train
  anno_path: train/_annotations.coco.json
  dataset_dir: *dataset_path
  data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  name: COCODataSet
  image_dir: valid
  anno_path: valid/_annotations.coco.json
  dataset_dir: *dataset_path
  allow_empty: true

TestDataset:
  name: ImageFolder
  anno_path: valid/_annotations.coco.json # also support txt (like VOC's label_list.txt)
  dataset_dir: *dataset_path
